# Generated by Django 5.2.4 on 2025-07-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appointments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'owners',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'pets'
                
            },
        ),
        migrations.CreateModel(
            name='PetVaccines',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time_of_vaccination', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pet_vaccines'
                
            },
        ),
        migrations.CreateModel(
            name='Vaccines',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vaccines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vets',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'vets',
                'managed': False,
            },
        ),
    ]
